### ISSUE TITLE
error

### ISSUE THREAD

**Issue by NaldoMota1** [SlavyanDesu/elaina-bot#3]
![erro maldito](https://user-images.githubusercontent.com/71650872/99253833-30d79080-27f0-11eb-9081-8b81a9b969ff.PNG)

**Comment by NaldoMota1** [comment]
this damn mistake continues

**Comment by SlavyanDesu** [comment]
> this damn mistake continues

Did you have Visual Studio Code or text editor installed on your PC? If so, open file `elaina-bot/message/text/lang/ind.js` and search for
```js
Vexports.wait = () => {
    // some code
}
```
Rename the `Vexports` to `exports`, this error happen because I did a typo. I'm so sorry :'v

**Comment by NaldoMota1** [comment]
> > this damn mistake continues
> 
> Did you have Visual Studio Code or text editor installed on your PC? If so, open file `elaina-bot/message/text/lang/ind.js` and search for
> 
> ```js
> Vexports.wait = () => {
>     // some code
> }
> ```
> 
> Rename the `Vexports` to `exports`, this error happen because I did a typo. I'm so sorry :'v

working.Thanks

**Comment by SlavyanDesu** [comment]
> > > this damn mistake continues
> > 
> > 
> > Did you have Visual Studio Code or text editor installed on your PC? If so, open file `elaina-bot/message/text/lang/ind.js` and search for
> > ```js
> > Vexports.wait = () => {
> >     // some code
> > }
> > ```
> > 
> > 
> > Rename the `Vexports` to `exports`, this error happen because I did a typo. I'm so sorry :'v
> 
> working.Thanks

You're welcome!
